### ISSUE TITLE
Teleportation bar at the top of the screen doesn't disappear after a server crash

### ISSUE THREAD

**Issue by TenKotowsky** [BlossomMods/BlossomHomes#10]
The server has crashed before I finished teleporting and it looks like the boss bar at the top of my screen never got deleted. Now I'm stuck with it and can't do anything about it

![image](https://github.com/BlossomMods/BlossomHomes/assets/100159503/af585b7c-2f73-4ce3-85a1-fcacb346aca4)

**Comment by TenKotowsky** [comment]
I am not 100% if it's BlossomHome or BlossomTPA related as I don't remember which one was I using before the crash tho

**Comment by CodedSakura** [comment]
you should be able to remove it via the `/bossbar` vanilla command

i'll try to look into it and make a better fix for it (by reusing existing bossbar if it exists)

**Comment by CodedSakura** [comment]
fixed in https://github.com/BlossomMods/BlossomLib/commit/fe5e20a6163f144f819fe3b4cc6b26a41be0f334 (2.5.2)
