### ISSUE TITLE
Inventory get cleared on teleporation

### ISSUE THREAD

**Issue by AriaFantom** [BlossomMods/BlossomHomes#16]
My inventory get cleared when i teleport to a home

**Comment by CodedSakura** [comment]
uhh that is very much not supposed to happen at all

have you relogged since? it could be a desync between the server and client

if the issue is repeatable, i'd like to get the list of mods

**Comment by AriaFantom** [comment]
Yes i had to relogin back to the server and after that it got visible and also it caused a lag on the server too for like 50s

**Comment by CodedSakura** [comment]
it would be useful if you could provide the list of mods running on the server

**Comment by CodedSakura** [comment]
> [!WARNING]  
> due to inactivity i'm scheduling this issue for closure on 2024-06-20, unless anyone else has encountered this and can report, or the original author can provide a mod list (providing this issue can still be reproduced)
