### ISSUE TITLE
Setting more than 2 homes

### ISSUE THREAD

**Issue by Eavilaswayce** [BlossomMods/BlossomHomes#18]
Apologies if this has been mentioned before, but I can't for the life of me figure out how to allow more homes.

Changing the startHomes setting in the config file doesn't do anything.

Thank you

**Comment by CodedSakura** [comment]
it is a bit confusing and i should've put that in the readme, but the `startHomes` only affects new players who join the server and set a home for the first time. to change max homes after that you need to use the OP command `/homes set-max ...`

([it had been mentioned,](https://github.com/BlossomMods/BlossomHomes/issues/6#issuecomment-1794173003) but no worries)

**Comment by Eavilaswayce** [comment]
Thank you so much, you just resolved hours of headache haha, creating an issue was the only solution as I couldn't find it mentioned anywhere else and having been up all night it didn't even occur to me that I was searching open issues.

Thanks again :)
