### ISSUE TITLE
error deleting homes

### ISSUE THREAD

**Issue by timtornado** [BlossomMods/BlossomHomes#3]
we are able to set 2 homes but not able to delete the second named home 

an unexpected error occurred trying to execute that command

[2.0.5+1.19]

**Comment by fithwum** [comment]
just went to look at the update and it says [2.0.6+1.19.3] but the file says 1.19.4 

also would this possibly be compatible with 1.19.2?

we are still waiting for other mods to update that we like to use so for now we are still on 1.19.2

**Comment by CodedSakura** [comment]
i can (and probably should) backport BlossomHomes 2.0.6 to 1.19 - 1.19.2 tho

**Comment by CodedSakura** [comment]
closing as off topic
