### ISSUE TITLE
Homes list not saveing at all

### ISSUE THREAD

**Issue by fithwum** [BlossomMods/BlossomHomes#7]
server restart wipes out all homes that people create

**Comment by fithwum** [comment]
Minecraft: 1.19.2
BlossomLib: 2.5.1
BlossomHomes: 2.0.5

Yes the file is being created but there is nothing in it at all

**Comment by CodedSakura** [comment]
i'm assuming that you've made sure you're using the `+1.19` versions and not `+1.19.3`, right?

could you set `fileLogLevel` to `ALL` in `BlossomLib.json` and send the `logs/BlossomMods.log` file after starting the server, adding a home, and stopping the server?

**Comment by fithwum** [comment]
yes we are using the +1.19 version

cant see any problems in the log but the data file is still empty

[BlossomMods.log](https://github.com/BlossomMods/BlossomHomes/files/11090997/BlossomMods.log)

**Comment by CodedSakura** [comment]
oh, i think i've found where the bug is:https://github.com/BlossomMods/BlossomHomes/blob/cda154a6a5da667dd3410abc0abbbc26cbae27d1/src/main/java/dev/codedsakura/blossom/homes/HomeController.java#L200

will fix as soon as i can!

**Comment by fithwum** [comment]
Thank you for all your help and we will wait for an update whenever you get it out
